# Generated by Django 2.0.6 on 2018-06-27 09:12

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20180620_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenerurl',
            name='url',
            field=models.CharField(max_length=250, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
